<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../classes/LQBasic.php';

/**
 * Test class for LQAtom.
 * Generated by PHPUnit on 2010-09-17 at 20:49:03.
 */
class LQAtomTest extends PHPUnit_Framework_TestCase {

    /**
     * @var LQAtom
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new LQAtom;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
