<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../classes/LQBasic.php';

/**
 * Test class for LQContainer.
 * Generated by PHPUnit on 2010-09-17 at 20:49:05.
 */
class LQContainerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var LQContainer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new LQContainer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testFormatPrice().
     */
    public function testFormatPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAnsiToLocaleDate().
     */
    public function testAnsiToLocaleDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddStatusMessage().
     */
    public function testAddStatusMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCleanMessages().
     */
    public function testCleanMessages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetStatusMessages().
     */
    public function testGetStatusMessages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddStatusMessages().
     */
    public function testAddStatusMessages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
