<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../classes/LQUser.php';

/**
 * Test class for LQUser.
 * Generated by PHPUnit on 2010-09-17 at 20:49:18.
 */
class LQUserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var LQUser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new LQUser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
